### ISSUE TITLE
代码复现报错Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by whiteyyc** [NUSTM/GMNER#13]
<img width="728" alt="微信图片_20241128105131" src="https://github.com/user-attachments/assets/57889585-4edc-48bc-aef4-79d07391422d">

**Comment by whiteyyc** [comment]
尊敬的作者您好，我在复现您的代码时候出现 如上图的保存，这是在模型训练快结束的时候出现的，但是我发现即使这样依然有保存的模型，但是在我运行sh test.sh的时候就会出现：
not_cover: 8061
max_len_a:0.6, max_len:30
In total 3 datasets:
        train has 7000 instances.
        dev has 1500 instances.
        test has 1500 instances.

The number of tokens in tokenizer  50265
Some weights of BartModel were not initialized from the model checkpoint at /cy/caoyan/models/hf_model/facebook--bart-base and are newly initialized: ['encoder.img_proj.weight', 'encoder.img_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "test.py", line 127, in <module>
    model.load_state_dict(torch.load(args.model_weight))
  File "/cy/caoyan/software/anconda3/envs/gmner/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SequenceGeneratorModel:
        size mismatch for seq2seq_model.decoder.region_select.3.weight: copying a param with shape torch.Size([18, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for seq2seq_model.decoder.region_select.3.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([16]).
        这彷佛是参数的尺寸没对上，请教您在训练的时候有没有出过类似的问题，或者这两者中间的报错有没有联系呢

**Comment by zyLiRere** [comment]
应该是k的取值问题，从 16 改为 18
